reroll-recipe:
  - OAK_LOG
  - AIR
  - AIR
  - AIR
  - AIR
  - AIR
  - AIR
  - AIR
  - AIR

lucky-recipe:
  - STONE
  - AIR
  - AIR
  - AIR
  - AIR
  - AIR
  - AIR
  - AIR
  - AIR

remove-recipe:
  - DIRT
  - AIR
  - AIR
  - AIR
  - AIR
  - AIR
  - AIR
  - AIR
  - AIR

positive-effects:
  - SPEED
  - FAST_DIGGING
  - INCREASE_DAMAGE
  - HEAL
  - JUMP
  - REGENERATION
  - DAMAGE_RESISTANCE
  - FIRE_RESISTANCE
  - WATER_BREATHING
  - INVISIBILITY
  - NIGHT_VISION
  - HEALTH_BOOST
  - ABSORPTION
  - SATURATION
  - LEVITATION
  - LUCK
  - SLOW_FALLING
  - CONDUIT_POWER
  - DOLPHINS_GRACE
  - HERO_OF_THE_VILLAGE

negative-effects:
  - SLOW
  - SLOW_DIGGING
  - CONFUSION
  - BLINDNESS
  - HUNGER
  - WEAKNESS
  - POISON
  - WITHER
  - GLOWING
  - UNLUCK
  - BAD_OMEN
